language: python

python:
  - 3.6

addons:
  postgresql: "9.4"

services:
  - postgresql

env:
  - DJANGO=2.1.7

before_install:
  #include environment variables to be exported

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database ah_the_jedi;' -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  - coverage run --source=authors manage.py test
  - python -m coverage report -m

after_success:
  - coveralls
