# Generated by Django 2.1 on 2019-05-07 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0019_articlemodel_highlighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.TextField()),
                ('comment', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlighted_article', to='articles.ArticleModel')),
                ('highlighted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlighted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
