# Generated by Django 2.1 on 2019-05-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0003_highlightsmodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightsmodel',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
