# Generated by Django 2.1 on 2019-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0004_highlightsmodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightsmodel',
            name='location',
            field=models.TextField(),
        ),
    ]
