# Generated by Django 2.1 on 2019-05-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190508_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscriptions',
            name='app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unsubscriptions',
            name='email',
            field=models.BooleanField(default=False),
        ),
    ]
