# Generated by Django 2.1 on 2019-05-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20190509_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='app',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='email',
            field=models.BooleanField(default=True),
        ),
    ]
