# Generated by Django 2.2 on 2019-05-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20190509_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-createdAt']},
        ),
    ]
