# Generated by Django 2.2 on 2019-05-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20190520_0901'),
        ('notifications', '0006_auto_20190517_1220'),
    ]

    operations = [
    ]
