# Generated by Django 2.1 on 2019-04-29 18:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190429_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
