# Generated by Django 2.1 on 2019-04-29 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_auto_20190429_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='author',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='author',
            field=models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
