# Generated by Django 2.1 on 2019-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20190501_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
