# Generated by Django 2.1 on 2019-05-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20190501_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
