# Generated by Django 2.1 on 2019-05-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20190501_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
