# Generated by Django 2.1 on 2019-05-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_favoritearticlemodel'),
        ('articles', '0019_auto_20190506_0818'),
    ]

    operations = [
    ]
