# Generated by Django 2.2 on 2019-05-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20190506_0818'),
        ('articles', '0019_articlemodel_readtime'),
    ]

    operations = [
    ]
