# Generated by Django 2.1 on 2019-05-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20190502_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='twitter',
        ),
    ]
