# Generated by Django 2.1 on 2019-05-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_articlemodel_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='highlighted',
        ),
    ]
