# Generated by Django 2.2 on 2019-05-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_merge_20190508_0713'),
        ('articles', '0020_merge_20190508_0813'),
    ]

    operations = [
    ]
