# Generated by Django 2.1 on 2019-05-08 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0020_merge_20190508_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='num_vote_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='num_vote_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmarkarticlemodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleModel', to_field='slug'),
        ),
        migrations.AddField(
            model_name='bookmarkarticlemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
