# Generated by Django 2.1 on 2019-05-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20190506_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='linkedIn',
        ),
    ]
