# Generated by Django 2.2 on 2019-05-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_merge_20190508_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='num_vote_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='num_vote_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
    ]
