# Generated by Django 2.1 on 2019-05-08 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20190508_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkarticlemodel',
            name='bookmarked_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
