# Generated by Django 2.1 on 2019-05-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20190508_0741'),
        ('articles', '0020_merge_20190508_0813'),
    ]

    operations = [
    ]
