# Generated by Django 2.1 on 2019-05-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20190508_1300'),
        ('articles', '0025_merge_20190508_1042'),
    ]

    operations = [
    ]
