# Generated by Django 2.2 on 2019-05-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_merge_20190508_1042'),
        ('articles', '0022_auto_20190508_1110'),
    ]

    operations = [
    ]
