# Generated by Django 2.2 on 2019-05-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_merge_20190508_1224'),
        ('articles', '0026_merge_20190508_1408'),
    ]

    operations = [
    ]
