# Generated by Django 2.2 on 2019-05-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_merge_20190509_0858'),
        ('articles', '0026_merge_20190508_1403'),
    ]

    operations = [
    ]
