# Generated by Django 2.2 on 2019-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_merge_20190509_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='tagList',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tagList',
            field=models.ManyToManyField(to='articles.TagModel'),
        ),
    ]
