# Generated by Django 2.2 on 2019-05-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_comments', '0001_initial'),
        ('articles', '0028_merge_20190509_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_comment', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluent_comments.FluentComment')),
            ],
        ),
    ]
