# Generated by Django 2.2 on 2019-05-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_commenthistorymodel'),
        ('articles', '0029_auto_20190513_1142'),
    ]

    operations = [
    ]
