# Generated by Django 2.2 on 2019-05-15 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0029_auto_20190513_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadStatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_article', to='articles.ArticleModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
