# Generated by Django 2.2 on 2019-05-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='vote_down',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='vote_up',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='votes',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
