# Generated by Django 2.2 on 2019-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_auto_20190511_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='tagList',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tagList',
            field=models.ManyToManyField(related_name='articles', to='articles.TagModel'),
        ),
    ]
