# Generated by Django 2.2 on 2019-05-11 19:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_auto_20190511_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='articles.TagModel'),
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='tagList',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tagList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=128), blank=True, default=list, size=None),
        ),
    ]
