# Generated by Django 2.2 on 2019-05-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_auto_20190513_1142'),
        ('articles', '0030_auto_20190515_0707'),
    ]

    operations = [
    ]
