# Generated by Django 2.2 on 2019-05-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_merge_20190515_1309'),
        ('articles', '0030_merge_20190515_1421'),
    ]

    operations = [
    ]
