# Generated by Django 2.2 on 2019-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_auto_20190511_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagmodel',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles_tag', to='articles.TagModel'),
        ),
    ]
