# Generated by Django 2.2 on 2019-05-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_readstatsmodel'),
        ('articles', '0032_merge_20190516_1029'),
    ]

    operations = [
    ]
