# Generated by Django 2.2 on 2019-05-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_auto_20190511_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagmodel',
            old_name='tags',
            new_name='tagname',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='article',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='articles.ArticleModel'),
        ),
    ]
