# Generated by Django 2.2 on 2019-05-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_auto_20190511_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='article',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(to='articles.TagModel'),
        ),
    ]
