# Generated by Django 2.2 on 2019-05-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_merge_20190516_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='tagList',
            new_name='tag_list',
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
