# Generated by Django 2.2 on 2019-05-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_auto_20190511_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='tagList',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tagList',
            field=models.ManyToManyField(to='articles.TagModel'),
        ),
    ]
