# Generated by Django 2.2 on 2019-05-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_auto_20190517_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='favoritesCount',
            new_name='favorites_count',
        ),
    ]
