# Generated by Django 2.2 on 2019-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_auto_20190520_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
