# Generated by Django 2.2 on 2019-05-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='user',
            new_name='reporter',
        ),
    ]
