# Generated by Django 2.2 on 2019-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190513_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='reporter',
            new_name='user',
        ),
    ]
