# Generated by Django 2.2 on 2019-05-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190513_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='reporter',
            new_name='user',
        ),
    ]
