# Generated by Django 2.2 on 2019-05-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='author',
            new_name='reporter',
        ),
    ]
