# Generated by Django 2.2 on 2019-05-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20190514_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='reporter',
        ),
    ]
