# Generated by Django 2.2 on 2019-05-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190517_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
